// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopQueueScanner():void;

export function DeviceID():Promise<string>;

export function GetQueueLogs():Promise<string>;

export function QueueScanner():void;

export function RestartQueueScanner():void;
