// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueueScanner() {
  return window['go']['main']['App']['QueueScanner']();
}

export function GetQueueLogs() {
  return window['go']['main']['App']['GetQueueLogs']();
}
