// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeviceID() {
  return window['go']['main']['App']['DeviceID']();
}

export function GetQueueLogs() {
  return window['go']['main']['App']['GetQueueLogs']();
}

export function QueueScanner() {
  return window['go']['main']['App']['QueueScanner']();
}

export function RestartQueueScanner() {
  return window['go']['main']['App']['RestartQueueScanner']();
}

export function StopQueueScanner() {
  return window['go']['main']['App']['StopQueueScanner']();
}
